// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdHZWTkNuZZlPI_DcEdAYRC30HpRcFd9Q',
    appId: '1:183499407998:web:6064385512f60b950e0e2f',
    messagingSenderId: '183499407998',
    projectId: 'catalog-app-a4bf6',
    authDomain: 'catalog-app-a4bf6.firebaseapp.com',
    storageBucket: 'catalog-app-a4bf6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOcSXJPMRfiXo2OjBgUZOT-TJ2UUGM88o',
    appId: '1:183499407998:android:9d6dbcee1e2855450e0e2f',
    messagingSenderId: '183499407998',
    projectId: 'catalog-app-a4bf6',
    storageBucket: 'catalog-app-a4bf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8R9nG2HDa4jLxlNUn5D1iSNcJ7HxTrMk',
    appId: '1:183499407998:ios:98b31488fa6d70810e0e2f',
    messagingSenderId: '183499407998',
    projectId: 'catalog-app-a4bf6',
    storageBucket: 'catalog-app-a4bf6.appspot.com',
    iosClientId: '183499407998-sf2oghdoedlghf51n35mgd5rulmpkbqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8R9nG2HDa4jLxlNUn5D1iSNcJ7HxTrMk',
    appId: '1:183499407998:ios:98b31488fa6d70810e0e2f',
    messagingSenderId: '183499407998',
    projectId: 'catalog-app-a4bf6',
    storageBucket: 'catalog-app-a4bf6.appspot.com',
    iosClientId: '183499407998-sf2oghdoedlghf51n35mgd5rulmpkbqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );
}
